name: psana_env
channels:
 - lcls-i
 - conda-forge
 - cctbx
 - defaults
dependencies:
 # conda compilers
 - c-compiler
 - cxx-compiler
 - scons

 # psana
 - psana

 # python
 - python=3.7
 - biopython
 - ipython

 # testing
 - pytest
 - pytest-xdist

 # documentation
 - docutils
 - numpydoc
 - sphinx

 # graphics
 - pillow
 - reportlab
 - wxpython=4.0.*
 - pyopengl

 # HDF5 (main libraries come with psana)
 - hdf5-external-filter-plugins  # [unix]

 # other
 - libsvm
 - mrcfile
 - psutil

 # cctbx channel
 - libsvm_py

 # dials
 - jinja2
 - msgpack-python
 - orderedset
 - procrunner
 - python-blosc
 - scikit-learn
 - tqdm
 - eigen
 - dials-data

 # xia2
 - tabulate

 # Phenix
 - send2trash
 - PyRTF

 # xfel gui
 - mysql
 - mysql-connector-python
