name: psana_env
channels:
 - lcls-i
 - conda-forge
 - cctbx
 - defaults
dependencies:
 # conda compilers
 - c-compiler
 - cxx-compiler
 - scons

 # psana
 - psana

 # python
 - python=3.7
 - biopython
 - ipython

 # testing
 - pytest
 - pytest-xdist

 # documentation
 - docutils
 - numpydoc
 - sphinx

 # graphics
 - pillow
 - reportlab
 - wxpython
 - pyopengl

 # HDF5 (main libraries come with psana)
 - hdf5plugin  # [unix]

 # other
 - libsvm
 - mrcfile
 - psutil
 - mpi4py
 - pandas
 - pybind11

 # cctbx channel
 - libsvm_py

 # dials
 - jinja2
 - msgpack-python
 - orderedset
 - procrunner
 - python-blosc
 - scikit-learn
 - tqdm
 - eigen
 - dials-data

 # xia2
 - tabulate

 # Phenix
 - send2trash
 - PyRTF

 # xfel gui
 - mysql
 - mysql-connector-python

 # temporarily pin numpy version
 # See https://github.com/cctbx/cctbx_project/issues/627
 - numpy=1.20
