# Script for building CCTBX
# linux image descriptions
# https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/linux/Ubuntu1604-README.md

jobs:
- job: linux_64
  pool:
    vmImage: ubuntu-16.04
  timeoutInMinutes: 360
  dependsOn: syntax
  strategy:
    maxParallel: 3
    matrix:
      python2.7:
        CONDA: Linux
        OS: linux-64
        PYTHON_VERSION: py27
      python3.6:
        CONDA: Linux
        OS: linux-64
        PYTHON_VERSION: py36
  container:
    image: ${{ parameters.distribution }}:${{ parameters.version }}
    options: "--name ci-container -v /usr/bin/docker:/tmp/docker:ro"

  steps:
  # https://github.com/ApexAI/performance_test/blob/master/azure-pipelines.yml#L9-L17

  # centos setup
  - script: |
      /tmp/docker exec -t -u 0 ci-container \
      sh -c "yum install -y sudo"
    displayName: Set up sudo
    condition: eq('${{ parameters.distribution }}', 'centos')

  - script: |
      sudo yum groupinstall -y 'Development Tools'
      sudo yum install -y python-argparse mesa-libGLU-devel mesa-libGL-devel
    displayName: Install dependencies
    condition: eq('${{ parameters.distribution }}', 'centos')

  # ubuntu setup
  - script: |
      /tmp/docker exec -t -u 0 ci-container \
      sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo"
    displayName: Set up sudo
    condition: eq('${{ parameters.distribution }}', 'ubuntu')

  - script: |
      sudo apt-get install -y build-essential libgl1-mesa-dev libglu1-mesa-dev
    displayName: Install dependencies
    condition: eq('${{ parameters.distribution }}', 'ubuntu')

  # build
  - template: ./unix-install-miniconda.yml
  - template: ./unix-build.yml
