# Parameters:
#   modules: <modules artifact name>

jobs:
  - template: ./conda-win.yml
    parameters:
      vmImage: windows-2022
      vs: 2022
      modules: modules
  - template: ./conda-linux.yml
    parameters:
      distribution: cctbx/rockylinux
      version: [8]
      modules: ${{ parameters.modules }}
      template: ./unix-conda-build.yml
  - template: ./conda-osx.yml
    parameters:
      vmImage: [14]
      xcode_version: [15, 4]
      modules: modules
      template: ./unix-conda-build.yml
