# Parameters:
#   modules: <modules artifact name>

jobs:
  - template: ./conda-win.yml
    parameters:
      modules: modules
  - template: ./conda-linux.yml
    parameters:
      distribution: centos
      version: [6]
      modules: modules
  - template: ./conda-osx.yml
    parameters:
      vmImage: [10, 14]
      xcode_version: [11, 3, 1]
      modules: modules
