# Parameters:
#   modules: <modules artifact name>

jobs:
  - template: ./conda-win.yml
    parameters:
      vmImage: windows-2022
      vs: 2022
      modules: ${{ parameters.modules }}
  - template: ./conda-linux.yml
    parameters:
      distribution: cctbx/rockylinux
      version: [9]
      modules: ${{ parameters.modules }}
      template: ./unix-conda-build.yml
  - template: ./conda-linux.yml
    parameters:
      distribution: cctbx/rockylinux
      version: [8]
      modules: ${{ parameters.modules }}
      template: ./unix-conda-build.yml
  - template: ./conda-linux.yml
    parameters:
      distribution: ubuntu
      version: ['22', '04']
      modules: ${{ parameters.modules }}
      template: ./unix-conda-build.yml
  - template: ./conda-linux.yml
    parameters:
      distribution: ubuntu
      version: ['24', '04']
      modules: ${{ parameters.modules }}
      template: ./unix-conda-build.yml
  - template: ./conda-osx.yml
    parameters:
      vmImage: [15]
      xcode_version: [26, 2]
      modules: ${{ parameters.modules }}
      template: ./unix-conda-build.yml
  - template: ./conda-osx.yml
    parameters:
      vmImage: [15]
      xcode_version: [16, 4]
      modules: ${{ parameters.modules }}
      template: ./unix-conda-build.yml
  - template: ./conda-osx.yml
    parameters:
      vmImage: [14]
      xcode_version: [15, 4]
      modules: ${{ parameters.modules }}
      template: ./unix-conda-build.yml
